### ISSUE TITLE
task Update /etc/hosts regexp fix.

### ISSUE THREAD

**Issue by UrielCh** [angristan/ansible-wireguard#3]
bonjour Stanislas,

Merci pour ce role ansible, il m'a fait gagner pas mal de temps.

Cependant la tache:

```
- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[host]['wireguard_address'] }}"
    line: "{{ hostvars[host]['wireguard_address'] }} {{ host }}"
```

Ne fonctionne pas avec plus de 10 IP, car le point des IP sont interprete en tant que regexp.

pour corriger ca:
```
        regexp: "^{{ hostvars[host]['wireguard_address'] | regex_replace('\\.','\\\\.') }} "
        line: "{{ hostvars[host]['wireguard_address'] }} {{ host }}"
```

sans oublier au moins un espace a la fin de la regexp. si ce n'est un \s.

cordiallement,
